theme: minima
title: Sanket sathe site
author: sanketkumar sunil sathe 
email: sanketsunilsathe@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  By Grace Through Faith.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  sanketsathe # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
